const express=require('express');
const cors=require('cors');
const user = require('./routes/user.route');
const admin = require('./routes/admin.route');
const app=express();
app.use(express.json());
app.use(cors());
app.use('/files',express.static('uploads'));
app.use('/api/user/v1',user);
app.use('/api/user/v1',user);
app.use('/api/user/v1',user);
app.use('/api/user/v1',user);
app.use('/api/admin/categories/v1',admin);
app.use('/api/admin/categories/v1',admin);
app.use('/api/admin/categories/v1',admin);
app.use('/api/admin/products/v1',admin);
app.use('/api/admin/products/v1',admin);
app.use('/api/admin/products/v1',admin);

module.exports=app;